### ISSUE TITLE
かざぐるマウスと併用時、2021/06 以降の修正でAlt+F4がおかしな動作するようになった

### ISSUE THREAD

**Issue by leafytree** [smzht/fakeymacs#15]
作成ありがとうございます。日々利用させていただいております。

フリーソフト　かざぐるマウス　で、マウス拡張ボタンにAlt+F4を設定しております。
いつの頃からか、そのボタンを押すと、ファイルエクスプローラが閉じずに、アドレス欄がドロップする現象が、常時起こるようになりました。

他のアプリは、閉じられます。また、キーボードからalt f4は、問題なく動作します。

以前はそのようなことが無かったので、config.pyファイルをさかのぼってみると、
20210601分を利用した状況では、ファイルエクスプローラが、思い通りに閉じられます。
これ以降の修正で何か影響があったようなのですが、対応可能でしょうか？

**Comment by smzht** [comment]
いつもソフトウェアのご利用、ありがとうございます。

かざぐるマウスを使ったことがないのですが、一つ試してみていただけますか？

恐らくですが、かざぐるマウスでは  Alt+F4 の登録する際に実際にキーを押して登録しているのではないかと思います。その操作をする際に Keyhac のメニューから「フックをOFF」を選択してから行うようにしてみてください。

かざぐるマウスのキー登録が終わった後は、Keyhac の設定を元に戻して構いません。

2021/6/1 の修正で、Emacs キーバインドのキーマップにすべてのキーを登録するようにしました。これは、一つ前に入力したキーを記憶できるようにするため（Emacs日本語入力で使うため）なのですが、これが影響している可能性があります。

以上、確認よろしくお願いします。

**Comment by smzht** [comment]
Fakeymacs の以下のページ（トップページ）の留意事項３つ目に、私も嵌った同様の件の記載があります。
・https://github.com/smzht/fakeymacs
よろしくお願いします。

**Comment by smzht** [comment]
Alt キーに関連する不具合であることが分かりました。

以下で対応しましたので、確認よろしくお願いします。
- https://github.com/smzht/fakeymacs/commit/ee26e6c6f452d20f76a65e7063adbfc4ce0567aa

**Comment by smzht** [comment]
上記での対策箇所は、O-LAlt キーや O-RAlt キーを IME の切り替え等で使えるようにするための部分です。この判定がアルファベット O キーに反応していました。

ただし、O-LAlt キーや O-RAlt キーのキーは fc.toggle_input_method_key 変数や fc.set_input_method_key 変数で利用することを想定しているため、これらのキーに O-LAlt キーや O-RAlt キーのキーを設定すると「かざぐるマウス」の問題は再発する状況です。

この状況はいまのところ回避できないと思っておりますので、fc.toggle_input_method_key 変数や fc.set_input_method_key 変数を設定する際にはご留意いただければと思います。

以上、よろしくお願いします。

**Comment by leafytree** [comment]
修正出来ていること確認いたしました。


かざぐるマウスとの併用、alt単独押下、いずれも改善しております。

fc.～method_keyの注意点、ありがとうございます。
fc.set_input_method_keyに対して
C-LAlt/C-RAltで設定したところうまく動いていますので、これで様子見たいとおもいます。

このたびはすみやかなご対応ありがとうございました。
