### ISSUE TITLE
ライセンスはどのようになっていますか?

### ISSUE THREAD

**Issue by ncaq** [smzht/fakeymacs#17]
素晴らしいコードを利用したいのでライセンスを確認したい。

# 前提

私は、
<https://github.com/ncaq/.emacs.d/blob/b2c5f6404a4c8e75fbbc140b3204aea222235269/init.el#L88>
のように、
Emacs本体のキーバインドを主にDvorak向けにだいぶ改造しているので、
このFakeymacsをそのまま使ったり、
想定された設定オプションの範囲で使うことが出来ません。

なので、
[ncaq/keyhac-config](https://github.com/ncaq/keyhac-config)
にこのコードの一部をコピペするか、
モジュールとして呼び出すか、
もしくはこれをforkして使うか、
と言った選択をすると思います。

特にマークで選択出来るのを実現しているのは素晴らしく、
Windowsでとても実現したいと思っています。

# 問題

これらのコードのライセンスはどうなっていますか?

> スクリプトですので、使いやすいようにカスタマイズしてご利用ください。

となっていますが、
ここまで来ると普通にプログラミングなので、
ライセンスが気になっています。

元々Keyhacのライセンスが不明という問題はありますが、
とりあえずこの素晴らしいスクリプトコードのライセンスを知って安心して利用したいです。

**Comment by smzht** [comment]
やはり、ライセンス必要ですかね。次のページを読んで、ライセンスを設定しないことが逆に自由を制限していることが分かりました。
- https://qiita.com/Tatamo/items/ae7bf4878abcf0584291

制限の少ないMIT Lisence辺りをつけることを検討してみたいと思います。今しばらくお待ち下さい。

**Comment by smzht** [comment]
MIT Lisence を設定しました。よろしくお願いします。

**Comment by smzht** [comment]
Fakeymacs の機能を利用する際に、拡張機能として実装する方法があります。

Emacs キーバインドを拡張したものですが、vscode_key Extension などは参考になるのではないかと思います。

config_personal.py を _config_personal.py を複写して作成し、fc.not_emacs_target や fc.ime_target を空リストにすれば、新しいキーバインドを一から設定できます。

一つの拡張の方法として、ご検討いただければと思います。

**Comment by smzht** [comment]
もうひとつ方法がありました。

config_personal.py の中の fc.skip_settings_key では、キーマップ毎に設定をスキップするキーを指定できます。
不要なキー設定はこの変数の設定でスキップし、あとはコメントに書いているとおり、「-2」が付くセクション内で define_key2 関数を利用して定義し直すという方法があります。

こちらも検討してみていただければと思います。

**Comment by ncaq** [comment]
ありがとうございます。
とりあえずライセンスを設定してくださったため、このissueは閉じようと思います。
