### ISSUE TITLE
Excel のセル参照ができません

### ISSUE THREAD

**Issue by camelken** [smzht/fakeymacs#19]
commit  2840077618889b796f040e9a0dc68103419c3b4
以降、Excel のセル参照ができなくなりました。

1.  A1 にカーソルを置く
2.  "=" + "C-f"
3.  A1 は、"=" のまま (上記のコミット以前は、"=B1" となっていました。)
4.  A2 にカーソルを置く
5.  "=sum(" + "C-f" + "Space" + C-f" + ")"
6.  A2 は、"=" のまま (上記のコミット以前は、"=sum(B2:C2)" となっていました。)

ご確認くださいませんでしょうか。
よろしくお願いいたします。

**Comment by smzht** [comment]
develop branch に上記の対策コミットを追加しました。
確認をお願いします。

**Comment by smzht** [comment]
この対策で多くのCtrlを利用するキーバインドに遅延が発生するので、もう少し対策が必要そうです。
まずは上記コミットで暫定対策にはなると思いますので、この対策をしばらくご利用ください。

**Comment by smzht** [comment]
上記コミットで追加改善を行いました。

**Comment by camelken** [comment]
ありがとうございます。
セル参照ができるようになりました。

**Comment by smzht** [comment]
master branch にマージし、この issue はクローズしたいと思います。
