### ISSUE TITLE
拡張選択（expand selection）を実装したい

### ISSUE THREAD

**Issue by DaikiSuganuma** [smzht/fakeymacs#21]
Visual Studio Codeなどにある拡張選択の機能を他のアプリケーションでも実装できればと思っております。

Visual Studio Codeのexpand selectionの説明はこちら。
https://code.visualstudio.com/docs/editor/codebasics

簡易的に
```
self_insert_command("C-Left", "C-S-Right")()
```
で単語を選択できるようにしておりますが、行先頭や文字先頭だとうまく機能しません。
カーソル位置の左右にある文字を取得するにはどうしたらよいでしょうか？

**Comment by smzht** [comment]
次のようにすると、少し良いかもしれません。
```
self_insert_command("C-Right", "C-Left", "C-S-Right")()
```

**Comment by DaikiSuganuma** [comment]
お返事ありがとうございます！
少し改善しました。

さらに次のようにできればと思っております。
- カーソル位置の左右文字を見て選択方向を決定（単語末にカーソルがある場合など）
- 選択状態ならば次のCtrl-Left, Ctrl-Rightまで選択拡張（カンマ手前まで）

このプログラムを書くために下記可能でしょうか？
- カーソル位置の左右の文字取得
- 選択状態かの判断

**Comment by smzht** [comment]
カーソル位置の左右の文字の取得は、文字を選択して C-c でクリップボードに取り込み、getClipboardText 関数により取り出せます。でも、後処理などいろいろ操作が必要になると思います。

また、選択状態かは fakeymacs.forward_direction 変数の値で判断できます。None で未選択、True で forward 方向にカーソルを動かして選択、False で backword 方向にカーソルを動かして選択です。キーボードで選択操作を行った時のみ設定される変数であり、マウスで設定した場合には設定されません。

以上、お試しください。

**Comment by DaikiSuganuma** [comment]
ご回答ありがとうございます！
簡単に実現できればと思ってましたが、しばらくは簡易的な選択で様子をみたいと思います。
お手数をおかけしました。
