### ISSUE TITLE
Windows11環境でCtrl-Spaceで選択モードをONにしたらCtrl関連のコマンドはIM切り替え動作になる

### ISSUE THREAD

**Issue by jiaqi228** [smzht/fakeymacs#25]
OS: Windows11 （22621.1413）
Installed IM：① Microsoft Chinese Pinyin Input　② Microsoft Japanese Input

Ctrl-Spaceで選択モードにして、移動コマンド「Ctrl-e」や「Ctrl-f」を実行したらIM切り替え動作になってしまいます。
Windows画面の右下にあるIM切り替えウィンドウが表示されますが、IMの切り替えは実質できません。
選択モードがONになっている間に、移動コマンドを押すと都度発生します。
Alt関連のコマンドでは問題ありません。
再度Ctrl-Spaceで解消できます。

当現象はFakeymacsの問題になりそうですか？またはロカールPC環境の問題になりそうですか？

**Comment by smzht** [comment]
以下を参考とし、Ctrl + Shiftの無効化設定をしてみてください。
- https://jill-tone.com/win10ime_ctrlshift_invalidation/

**Comment by jiaqi228** [comment]
> 以下を参考とし、Ctrl + Shiftの無効化設定をしてみてください。
> 
> * https://jill-tone.com/win10ime_ctrlshift_invalidation/

Ctrl+Shiftを無効に設定したら問題が解決しました。
ありがとうございました！

**Comment by smzht** [comment]
README に記載しておきました。

- https://github.com/smzht/fakeymacs#2-ime%E3%82%92%E5%88%87%E3%82%8A%E6%9B%BF%E3%81%88%E3%82%8B%E3%82%B7%E3%83%A7%E3%83%BC%E3%83%88%E3%82%AB%E3%83%83%E3%83%88%E3%82%AD%E3%83%BC%E3%82%92%E7%84%A1%E5%8A%B9%E5%8C%96%E3%81%99%E3%82%8B
