### ISSUE TITLE
Adobe Illustrator上でのスペース押下時の挙動

### ISSUE THREAD

**Issue by DaikiSuganuma** [smzht/fakeymacs#27]
毎日便利に使っております。
Adobe Illustrator（Adobe製品全般）使用時はKeyhacを無効化したいので下記記述を入れているのですが、スペースを押したときに画面移動できません（カーソルが手の形になり画面移動できる）。
Keyhacを終了すると思った通りの挙動になります。
何か追加の設定が必要でしょうか？
```
fc.not_emacs_target    += ["Illustrator.exe"]
fc.ime_target          += ["Illustrator.exe"]
```

**Comment by smzht** [comment]
fc.skip_settings_key の "keymap_base" に ”Space" を追加するとどうなるか試してみていただけますか？
```
fc.skip_settings_key    = {"keymap_base"      : ["*W-g", "Space"], # ベース Keymap
                           ...
                           }
```

**Comment by DaikiSuganuma** [comment]
ご回答ありがとうございます。
追記しリロードして試してみましたが、動作変わらないようです。
```
fc.skip_settings_key    = {"keymap_base"      : ["*W-g", "Space"], # ベース Keymap
                           "keymap_global"    : [],       # グローバル Keymap
                           "keymap_emacs"     : [],       # Emacs キーバインド対象アプリ用 Keymap
                           "keymap_vscode"    : [],       # Emacs キーバインド VSCode 拡張用 Keymap
                           "keymap_ime"       : [],       # IME 切り替え専用アプリ用 Keymap
                           "keymap_ei"        : [],       # Emacs 日本語入力モード用 Keymap
                           "keymap_tsw"       : [],       # タスク切り替え画面用 Keymap
                           "keymap_lw"        : [],       # リストウィンドウ用 Keymap
                           }
```

**Comment by smzht** [comment]
config.py を以下のとおりにした場合、どうなるでしょうか？
````
import pyauto
from keyhac import *

def configure(keymap):
    pass
````

**Comment by DaikiSuganuma** [comment]
ありがとうございます。
config.pyをご指摘の通りの5行だけにしてリロードしたら、Illustratorでスペースが意図した通りに動きました！
config.py上の何かが原因のようですね。
対応策を教えていただけますと幸いです。

**Comment by smzht** [comment]
fc.skip_settings_key の設定は、config_personal.py に対して行ったか確認させてください。
あと、config.py の初めにある、fakeymacs_version の値を教えてください。

**Comment by DaikiSuganuma** [comment]
ありがとうございます。
GitHubで公開しておりますので、何か間違いなどあればご指摘いただけますと幸いです。
https://github.com/DaikiSuganuma/fakeymacs

fakeymacs_version = "20230628_01"

**Comment by smzht** [comment]
fc.skip_settings_key の設定は、config_personal.py に対して行ったか教えてください。

**Comment by DaikiSuganuma** [comment]
言葉足らずで失礼しました。
追記のfc.skip_settings_keyはconfig_personal.py に対して行っております。

またdefine_key関数の中でif文を入れてみたら意図した通りに動きました。
原因が分かりますでしょうか？
```
    def define_key(window_keymap, keys, command, skip_check=True):
        ...
        if keys == "Space": # このif文を追加してみました。
            return

        if keys is None:
            return
        ...
```

**Comment by DaikiSuganuma** [comment]
私の設定が間違っておりました。
指示のとおり、fc.skip_settings_keyの"keymap_base"に入れるべきところを"keymap_global"に設定しておりました。
失礼しました。

無事快適になりました。
ありがとうございます！

**Comment by smzht** [comment]
改善して良かったです。keymap_base は、入力したキーを記録するためや jis->us 配列変換するために設定している最下層の keymap 層なのですが、とりあえず Space は除外しても問題ないと思います。

ということで、本件クローズさせていただきます。
