### ISSUE TITLE
fc.skip_settings_key が反映されない

### ISSUE THREAD

**Issue by camelken** [smzht/fakeymacs#3]
fc.skip_settings_key が反映されないのですが、特別な方法がございますでしょうか。
GitHub から pull した状態の config.py と config_personal.py で以下の設定をしても反映されません。
Google 日本語入力で、ことえりのキーバインドで利用しています。
Fakeymacs ver.20200813_01 では、同じ設定で反映(無視)されます。
変換中に "C-e" で「前候補を選択」として動きます。
fc.skip_settings_key 以外の設定は、反映されているようです。
fc.skip_settings_key = {"keymap_global" : [],
                                    "keymap_emacs" : [],
                                    "keymap_ime" : [],
                                    "keymap_ei" : ["C-e"],
                                    "keymap_tsw" : [],
                                    "keymap_lw" : [],
                                    "keymap_edit_mode" : [],
                                    }

**Comment by smzht** [comment]
確認しますので、しばらくお時間ください。

**Comment by smzht** [comment]
原因分かりました。バグです。以下の警告にハマっています。対応策を検討します。

https://docs.python.org/ja/3/tutorial/controlflow.html#default-argument-values
重要な警告: デフォルト値は 1 度だけしか評価されません。

**Comment by smzht** [comment]
対応しました。（もとのコーディング方法に直しました。）確認ください。

https://github.com/smzht/fakeymacs/commit/96bea1578731ae9c9ec9b9091a1fbd7ac8971777

**Comment by camelken** [comment]
ありがとうございます。
fc.skip_settings_key が反映されるようになりました。

**Comment by smzht** [comment]
もう少し良い方法がないか検討していますが、今のところ変わりの良い方法は見つかっておりません。
まずは今のコードでお使いください。よろしくお願いします。
