### ISSUE TITLE
ターミナルアプリからアプリを実行した場合にショートカットが実行されない

### ISSUE THREAD

**Issue by izumi0x01** [smzht/fakeymacs#33]
コマンドプロンプト、gitbash等のターミナルアプリから任意のアプリを起動した際に、起動した先のアプリケーションでemacsショートカットが操作できないのですが、反映する方法はありますでしょうか？

fakeymacs の version は下記になります。
fakeymacs_version = "20230930_01"

例)
●ターミナルアプリ上でコマンドの指定
notepad.exe　→　反映されない
start notepad.exe　→　反映されない
●ターミナルアプリを介さずに任意のアプリを起動
ファイル名を指定して実行（win+R）上でnotepadを指定して実行　→　反映される

**Comment by smzht** [comment]
Keyhac のメニューから「内部ログをON」を選択し、emacs キーバインドが反映されない状態の notepad.exe を選択した場合にKeyhac コンソールに表示される exe 名と class 名を教えてください。

**Comment by izumi0x01** [comment]
コメントありがとうございます。

コマンドプロンプトからnotepad.exeを実行した場合のexe名とclass名は以下のようにkeyhackターミナルに表示されます。

Window : exe   : Notepad.exe
       : class : Notepad

（外部の適当なwindowを操作した後、notepadを操作する）

Window : exe   : Notepad.exe
       : class : RichEditD2DPT

========

また、notepad.exeを
●win+R上から実行した場合と
●コマンドプロンプトから実行した場合
実行した場合の２つについて動作を以下に比較します。

●コマンドプロンプトからnotepad.exeを実行した場合

Window : exe   : Notepad.exe
       : class : Notepad
       : text  : メモ帳

（任意のキーを入力）

表示に変化なし

●win+Rからnotepad.exeを実行した場合

Window : exe   : Notepad.exe
       : class : Notepad
       : text  : メモ帳

（任意のキーを入力）

Window : exe   : Notepad.exe
       : class : RichEditD2DPT
       : text  : 

IN  : D-A
OUT : [Key(65)]
IN  : U-A
TRU : U-A
IN  : O-A

（以下、キーの入力に応じて表示が変化する）

**Comment by smzht** [comment]
お使いの OS は Windows 11 だと思いますが、こちらの Windows 11 環境では発生しない問題となっています。
Keyhac の config.py を次の設定のみとして「内部ログをON」とした場合、上記と同様にキーログが表示されない症状が発生するか、確認をお願いできますでしょうか。
```
from keyhac import *

def configure(keymap):
    pass
```

**Comment by izumi0x01** [comment]
自身もwindows11で、config.pyを上記のとおりに変更して実行しました。
すると、上記の現象について、「windows terminal」から「コマンドプロンプト」や「gitbash」等のアプリを開いた場合に設定が反映されないことが確認できました。
「コマンドプロンプト」や「gitbash」等をスタートアップメニューから直接開いたうえで、notepad.exe等の任意のアプリを起動しようとすると設定が反映されることが確認できました。

**Comment by smzht** [comment]
次のページに (c) に該当する感じですかね。

- https://jingyo.seesaa.net/article/201101article_8.html

まずは、原因が分かって良かったです。

**Comment by izumi0x01** [comment]
実際、notepad.exeを管理者権限で実行すると設定が反映されなかったので、まさしくその現象の影響だと思います

**Comment by smzht** [comment]
本件、クローズとさせていただきますね。
また何かありましたら、問い合わせください。
