### ISSUE TITLE
スペースキーで youtube動画 の停止/再開ができない

### ISSUE THREAD

**Issue by sarami55** [smzht/fakeymacs#34]
タイトル通りなのですが、動画を一時停止したくても、スペースキーではできないようです。
いままではできていたと思うのですが。

fakeymacs_version = "20231019_01"

keyhac 単体だと 停止/再開はできます。
当然、フックOFFでもできます。

**Comment by elfham** [comment]
私も最近同じ症状になりました。
YouTube 動画再生だとスペースが高速に二回押されたかのように「再生→停止→再生」となる感じです。
ただ、私の手元のバージョンは 20220408_04 と古いままだったので、
ブラウザー (Google Chrome) 側の更新が関係するような気もします。

**Comment by sarami55** [comment]
firefoxでためしてみても現象は起きます。

**Comment by smzht** [comment]
報告ありがとうございます。こちらでも再現しました。SpaceFN拡張機能をONにしていると発生しない問題のようで、気がついていませんでした。SpaceFN拡張機能を作った時になんらかの影響が出たのかもしれません。
調べてみます。

**Comment by smzht** [comment]
KeyhacのフックをOFFにすると発生しない問題なので、Fakeymacsの問題の可能性が高いです。

**Comment by smzht** [comment]
elfhamさんの報告では、20220408_04版 でもなるのですね。だと、SpaceFN拡張機能のときの修正は関係なさそうです。

**Comment by smzht** [comment]
以下のコードでも再現します。Fakeymacs の問題ではなさそうですが、回避策が無いか検討してみます。
```
from keyhac import *

def configure(keymap):
    keymap_global = keymap.defineWindowKeymap()
    keymap_global["Space"] = "Space"
```

**Comment by smzht** [comment]
とりあえずの回避策です。config_pesonal.py の fc.skip_settings_key の設定を以下の通り変えてください。（二箇所に "Space” を追加する。
```
fc.skip_settings_key    = {"keymap_base"      : ["*W-g", "Space"], # ベース Keymap
                           "keymap_global"    : [],       # グローバル Keymap
                           "keymap_emacs"     : ["Space"],       # Emacs キーバインド対象アプリ用 Keymap
                           "keymap_vscode"    : [],       # Emacs キーバインド VSCode 拡張用 Keymap
                           "keymap_ime"       : [],       # IME 切り替え専用アプリ用 Keymap
                           "keymap_ei"        : [],       # Emacs 日本語入力モード用 Keymap
                           "keymap_tsw"       : [],       # タスク切り替え画面用 Keymap
                           "keymap_lw"        : [],       # リストウィンドウ用 Keymap
                           }
```

**Comment by smzht** [comment]
上記の方法以外に SpaceFN 拡張機能を有効にする方法もあります。これを機会に SpaceFN 拡張機能の評価を兼ねて使ってみていただき、問題等あれば報告していたけるとうれしかったりします。:-)

本体での回避策については引き続き検討します。

**Comment by smzht** [comment]
YouTube は Space キーを押した時と離した時にそれぞれ反応していますね。

**Comment by smzht** [comment]
とりあえず、以下だとうまくいくことが分かりました（"D-” を追加）。
```
from keyhac import *

def configure(keymap):
    keymap_global = keymap.defineWindowKeymap()
    keymap_global["Space"] = "D-Space"
```

**Comment by smzht** [comment]
config.py の 1377行目（space 関数の中）の sefl_insert_command の行を次のとおりとすると、改善します。
```
            self_insert_command("D-Space")()
```
他に影響がでないか、少し確認してみます。

**Comment by smzht** [comment]
上記に変更する影響度が分からないので、とりあえず今回の問題を対策する拡張機能 youtube_space_key を作りました。

- https://github.com/smzht/fakeymacs/commit/54fed7bc8ed1753fe96e48c4239f82f65b8c3d12

今回の問題がいつか改善されることを願って、それまで本拡張機能をご利用ください。

**Comment by elfham** [comment]
対応ありがとうございます。
早速 Fakeymacs と `config_personal.py` を更新して、 Windows 10 22H2 の Chrome, Edge, Firefox でスペースキーで再生・停止ができるようになったことを確認しました。

**Comment by sarami55** [comment]
当方も動作確認しました。
素早い対応ありがとうございました。

**Comment by smzht** [comment]
確認ありがとうございます。他にもこの問題に遭遇する方が居ると思いますので、この Issue はしばらく Open のままにしておこうかと思います。しばらくしたら、私が Close したいと思いますので、よろしくお願いします。

**Comment by smzht** [comment]
10/17 に次の update 情報が公開されていました。

- https://blog.youtube/news-and-events/youtube-new-features-2023/

この update によって発生するようになった問題のような気がします。

**Comment by smzht** [comment]
space_fn 拡張機能と youtube_space_key 拡張機能が共存できるように見直しを行いました。

- https://github.com/smzht/fakeymacs/commit/81337912ceecaecd3b0add346e772cb9000e0adc

これで、両拡張機能を有効にした場合、Space+b で YouTube の２倍速再生ができるようになりました。

**Comment by smzht** [comment]
ちょっとコードの見直しを行いました。機能に変更はありません。

- https://github.com/smzht/fakeymacs/commit/3dd4e2289f144da03653c4edde57d191e5f71905

**Comment by smzht** [comment]
本件、close とします。問い合わせありがとうございました。
