### ISSUE TITLE
chrome内で fc.emacs_ime_mode_key が動作しない

### ISSUE THREAD

**Issue by sarami55** [smzht/fakeymacs#36]
お世話になります。

chome内で検索など、日本語変換するときに ことえりキーの置き換えができていないように思われます。
firefox では問題ありません。

GitHub 最新バージョンです。

**Comment by smzht** [comment]
簡単に確認したところでは、こちらの環境では発生しない問題のようです。もしよろしければ、config.py と config_personal.py を smzhts1@gmail.com 宛に送っていただければ、こちらで調べてみることができます。以上、よろしくお願いします。

**Comment by sarami55** [comment]
送りました。

**Comment by smzht** [comment]
すみません。メールが振り分けられていて気づいていませんでした。
確認しますので、少しお時間ください。

**Comment by smzht** [comment]
設定の問題では無いようでした。一つ試してみていただきたいのですが、chromeの検索で日本語入力をし、F6、F7、F8、F9、F10を入力した場合、変換が正しく機能するか確認していただけますか？

**Comment by sarami55** [comment]
おせわになります。
想定通りに変化するようです。

F6 ひらがな
F7カタカナ
F8 半角カタカナ
F9 全角英字
F10 半角英字

**Comment by sarami55** [comment]
すみません。chrome上ではIMEのカラー設定などが無視されるようです。
そのため、Ctrl-O Ctrl-I が効いていないように見えていたようです。
皆さんのところではどうですか。

**Comment by smzht** [comment]
旧Microsoft IMEの場合、chrome上で文節長変更が正しく表示されないようです。（変換すると文節長が変更されているのが確認できるので、表示上の問題のようです。）この問題は、新Microsoft IME や Google 日本語入力では発生しておりません。
以上、よろしくお願いします。

**Comment by smzht** [comment]
とりあえず、次の設定で使ってみてください。

config_personal.py の fc.emacs_ime_mode_key 変数の最初の2行を次のとおりに変更する。
```
fc.emacs_ime_mode_key += [["C-i", ["S-Left", "Right", "Left"]],  # 文節を縮める
                          ["C-o", ["S-Right", "Left", "Right"]], # 文節を伸ばす
```

config.py の 2460行目を次のとおりに変更する。（self_insert_command 関数内の引数の先頭に「*」を追加する。）
```
            define_key(keymap_ei, replace_key, self_insert_command(*original_key))
```

リポジトリの config.py の変更については、今後検討したいと思います。以上、よろしくお願いします。

**Comment by smzht** [comment]
config.py の修正は行いました。

- https://github.com/smzht/fakeymacs/commit/0e1bf74cd12bc61bd26eadceb84946beb3f0d86e

**Comment by smzht** [comment]
configuration parameter 側の修正も行いました。

- https://github.com/smzht/fakeymacs/commit/85691e3bc745d3159c6b567da8d073e99dc7e819

もし不都合があればお知らせください。

**Comment by sarami55** [comment]
お世話になります。

old MS-IMEをあきらめるのがただしいのかもしれませんが、
カラー設定を利用したいので考えところです。

バリアフリーなデザインとして、カラー設定は今後使わないのかもしれません。
(色に頼らないで、フォント、下線などで対応する)

**Comment by smzht** [comment]
今回の対策で、色も正しく表示されるようになっていますので、お試しいただければと思います。

**Comment by sarami55** [comment]
ATOKのカラー設定なのですが、当方の環境ではうまくいきません。
chromeのテーマとの兼ね合いがあると思うので諦めます。 ( Material Simple Dark Grey)
MS-IMEのカラー設定だとうまくいくので、こちらを使います。

**Comment by smzht** [comment]
ATOKの環境は持っていないので確認できていません。
MS-IMEは改善したと思いますのでご了承ください。
以上、よろしくお願いします

**Comment by smzht** [comment]
旧MS-IMEの色設定をATOKにしたときの問題ですね。
少し調べてみますが、Fakeymacsの問題ではないため、対応は難しそうです。

**Comment by smzht** [comment]
chrome以外で正常に動作していなくなっていたことに気づきました。
一旦、configuration parameter 側の修正を元に戻します。
後ほど、chrome系ブラウザの場合のみ文節長変更時の入力キーを変える対応に見直したいと思います。

**Comment by smzht** [comment]
拡張機能として実装し直しました。chrome 系ブラウザ以外でも正常に動作すると思います。

- https://github.com/smzht/fakeymacs/commit/90a16a339570f5cb91de80c57c2114debc422d8c

なお、色指定を ATOK とした場合の対策は見つけられませんでした。
この対策で問題ないようであれば、本 issue の対応は完了にしようかと思います。

**Comment by sarami55** [comment]
問題なく動きました。
ご対応ありがとうございました。

**Comment by smzht** [comment]
bunsetsu_correction 拡張機能を有効にしても ATOK 色設定にするとうまく動かない件ですが、ATOK 色設定の「変更」で「注目文節内文字」の「下線」を「太線」にすると、chrome 系ブラウザでは MS-IME の色設定のように動くようです。
chrome 系ブラウザ以外では、ATOK の色設定で動いているように見えます。
理由は分かりませんが、使える方法のように思います。お試しください。

**Comment by sarami55** [comment]
情報ありがとうございます。

そもそも、chromeのいつのバージョンからおかしくなったでしょうね。
前はふつうにつかっていたはずですが。

**Comment by smzht** [comment]
以下のサイトでは、chrome 75から発生するようになったと書かれています。この時は Google 日本語入力でも発生していたようですが、こちらはその後対策されたのだと思います。旧 Microsoft IMEについては、新 Microsoft IMEが出た関係で対策されずに不具合が残っているといった感じでしょうか。
- https://support.google.com/chrome/thread/7458273/%E6%97%A5%E6%9C%AC%E8%AA%9E%E5%85%A5%E5%8A%9B%E4%B8%AD%E3%81%AE%E5%AF%BE%E8%B1%A1%E6%96%87%E7%AF%80%E3%81%AE%E5%A4%AA%E7%B7%9A%E3%81%8C%E6%96%87%E7%AF%80%E3%82%92%E7%A7%BB%E5%8B%95%E3%81%97%E3%81%A6%E3%82%82%E8%A1%A8%E7%A4%BA%E3%81%8C%E6%9B%B4%E6%96%B0%E3%81%95%E3%82%8C%E3%81%AA%E3%81%84?hl=ja

**Comment by smzht** [comment]
本件、close とさせていただきます。問い合わせありがとうございました。

**Comment by smzht** [comment]
今回の対策でデグレードを起こしていました。その対策を行いました。

- https://github.com/smzht/fakeymacs/commit/e5bd4d4fce30254bd46d791fed43f484a31c0289
