### ISSUE TITLE
Shiftキーのワンショットモディファイヤー　日本語変換On/Offで、変換確定できなくなる

### ISSUE THREAD

**Issue by leafytree** [smzht/fakeymacs#37]
いつも、利用させていただいております。

日本語変換On/Off切り替えのために、
左Shift:Off/右Shift:On
となるよう、config_personal.pyの最終行に以下の記述を追加しています。

```python
    define_key(keymap_global, "O-LShift", lambda: disable_input_method())
    define_key(keymap_global, "O-RShift", lambda: enable_input_method())
``` 

右Shiftで、日本語変換OnするとEnterで、日本語変換の確定ができなくなり、
おかしな状態となることがあります。
Shiftキーなど連打後に、しばらく静観すると、確定できるようになります。

特に、MS Teamsで良く遭遇する感覚です。ランダムに発生しますが、頻度は、2割ぐらいでしょうか。

なにか解決方法ございますでしょうか

**Comment by smzht** [comment]
上記の症状が発生した際に a のキーを押すとどうなるでしょうか？
A になるのであれば、Shift キーが押しっぱなしの状態になっていると思われます。

とりあえず、上記のコードを以下にして、しばらく使ってみていただけますか？
```
    keymap_global["O-LShift"] = disable_input_method
    keymap_global["O-RShift"] = enable_input_method
```

これでも発生するとなると、Fakeymacs の問題ではない可能性が高くなるので、対策は難しいかもしれません。

**Comment by leafytree** [comment]
ありがとうございます。いただいた、コードで一週間ほど様子を見ます。
結果は、改めてご連絡します。

**Comment by leafytree** [comment]
その後、頂いたコードでも、改善することはできませんでした。

また、シフトキーの押しっぱなしとは違うようで、事象発生中に、oキーを押すと、[o]と表示されました。aキー押下すると、[あ]と表示。

もう少し、環境変えてみて違いが出ないか確認してみます。

お気づきの点ございましたら、お知らせください

**Comment by smzht** [comment]
最新のコミットで、IME を切り替えるためのキーの設定を変更しました。
この最新のコミットでも現象が発生するか、試してみていただけますか？

これでも発生する場合は、変換キーに Shift を使っている辺りが関係しているような気はします。

**Comment by leafytree** [comment]
対応版のコミットで、数日動作確認をして、
現象が発生しなくなったことが確認できました。

ありがとうございました。 非常に助かりました。

**Comment by smzht** [comment]
改善したとのこと。良かったです。
本 issue はクローズしますので、現象が再発するようであればリオープンしてください。
よろしくお願いします。
