### ISSUE TITLE
ブラウザ内ターミナルでのemacsキーバインドの無効化について

### ISSUE THREAD

**Issue by k9i** [smzht/fakeymacs#39]
AWS Cloud9/CloudShell や GCP Cloud Shell のようなブラウザ内ターミナルについて、emacs キーバインドを無効化する設定はありますでしょうか？

(最近ブラウザ内ターミナルやエディタを使う機会が増えており、自動切替できると助かります)

**Comment by smzht** [comment]
fc.game_app_list というコンフィグレーションパレメーターがありますので、以下のような設定を追加してください。

```
fc.game_app_list += [["chrome.exe", "Chrome_WidgetWin_1", "（ブラウザ内ターミナルのウィンドウタイトル）"]]
```

追加するリストは、ウィンドウのプロセス名、ウィンドウのクラス名、ウィンドウのタイトルの順番で記載してください。
上記はプラウザが Chrome の場合の例です。「（ブラウザ内ターミナルのウィンドウタイトル）」の箇所は、ブラウザ内ターミナルのウィンドウタイトルに置き換えてください。「*」（アスタリスク）などのワイルドカードも利用できます。

最後に、開いているサイトをアプリとして登録してください。次のページの留意事項の６つめと７つめの ● にあるリンクが参考となります。
- https://github.com/smzht/fakeymacs/tree/master/fakeymacs_extensions/vscode_key#%E7%95%99%E6%84%8F%E4%BA%8B%E9%A0%85

アプリとして登録することにより、C-F4 や C-Tab など、プラウザに奪われるキーがプラウザに奪われずに入力できるようになります。

なお、game_app_list に適用されるキーマップは次にある図を参考としてください。

- https://github.com/smzht/fakeymacs/tree/master?tab=readme-ov-file#%E3%82%AD%E3%83%BC%E3%83%9E%E3%83%83%E3%83%97%E3%81%AE%E3%83%AC%E3%82%A4%E3%83%A4%E3%83%BC%E6%A7%8B%E6%88%90

以上、お試しください。

**Comment by k9i** [comment]
早速のご回答、ありがとうございます。
教えていただいた内容を試してみます。

**Comment by smzht** [comment]
設定の説明が不明確だったので、見直ししておきました。

- https://github.com/smzht/fakeymacs/commit/bf795cb61b0ada225bd520ccc2d9993114137c4e

**Comment by smzht** [comment]
上記で説明した fc.game_app_list 変数の指定方法は、現在、fc.not_emacs_target 変数や fc.ime_target 変数にも利用できます。これらの変数で指定した場合、keymap_base キーマップが通ることによる JIS->US 配列の変換機能が使えることや IME 利用時に Emacs 日本語入力モードが使えることなど、いくつかの利点があります。ご利用の場面に応じて使い分けていただければと思います。
