### ISSUE TITLE
ESC キーの長押しについて

### ISSUE THREAD

**Issue by elfham** [smzht/fakeymacs#43]
最近「偽セキュリティ警告（サポート詐欺）」というのが流行っているそうです。

ブラウザーでインターネットを閲覧中に偽物のセキュリティ警告画面を全画面で表示して偽のサポート電話番号に電話を掛けさせて詐欺へ誘導するというものです。

IPA がこの警告画面の体験サイトを公開していて、これを再現できるようになっています。

* [偽セキュリティ警告（サポート詐欺）対策特集ページ \| 情報セキュリティ \| IPA 独立行政法人 情報処理推進機構](https://www.ipa.go.jp/security/anshin/measures/fakealert.html)

この全画面表示は、通常のキーボードやマウス操作では閉じることが困難なのですが、 ESC の長押しで全画面表示を解除することができます。

しかしながら、 fakeymacs を有効にしていると、この ESC キーの長押しが効かなくなってしまうようです。

そこで、 ESC の長押しへの対応、あるいは何らか代替手段で ESC の長押し相当の機能があると便利なように思うのですが、いかがでしょうか？

**Comment by smzht** [comment]
Windows+m ですべてのウィンドウを最小化して、メニューバーにあるブラウザを右クリックで「閉じる」ではどうでしょうか？

この他にも、Windowsキーを二回押した後にF11キーで最大化解除するなど、いくつか方法があるようです。

**Comment by smzht** [comment]
ちょっと特殊な環境でテストをしていました。改めて、以下ではどうでしょうか？

1. Ctrl+Alt+Del を押す
2. 「タスクマネージャー」をクリックする
3. タスクマネージャーが開き、メニューバーが表示されるようになるので、Keyhac のアイコンを右クリックして、「フックを OFF」をクリックする
4. 元の「サポート詐欺」の画面をクリックし、Esc を長押しする

**Comment by smzht** [comment]
以下の対応でOKでした。

1. Ctrl+Alt+Del を押す
2. 「タスクマネージャー」をクリックする
3. タスクマネージャーが開き、メニューバーが表示されるようになるので、ブラウザアイコンにマウスカーソルを当て、ポップアップした「サポート詐欺」の画面にある「☓」をクリックする

**Comment by elfham** [comment]
早速試してみました。いずれの 2 つの方法でもバッチリいけました。

＃ 個人的な好みは、対象のタブだけ閉じるなどの操作がし易いので前者ですかね……。

これで対応できそうです。ありがとうございます。

**Comment by smzht** [comment]
対応方法が見つかりましたので、close とします。Esc の長押しの方法があること、参考となりました。ありがとうございました。
