### ISSUE TITLE
ERROR : 設定ファイルの実行中にエラーが発生しました.

### ISSUE THREAD

**Issue by camelken** [smzht/fakeymacs#6]
コミットハッシュ 0a8723d15d9a70952685fd9d8ee680bced6776b3 の
config.py と _config_personal.py で以下のエラーになります。

Fakeymacs version 20200923_04:
  https://github.com/smzht/fakeymacs

ERROR : 設定ファイルの実行中にエラーが発生しました.
Traceback (most recent call last):
  File "../ckit\ckit_userconfig.py", line 42, in callConfigFunc
  File "config.py", line 2345, in configure
    exec(readConfigPersonal("[section-base-2]"), dict(globals(), **locals()))
  File "<string>", line 48
    if 0
       ^
SyntaxError: invalid syntax
設定ファイルをリロードしました.

**Comment by camelken** [comment]
これで、エラーは解消されました。

$ diff -urNp _config_personal.py.orig _config_personal.py
--- _config_personal.py.orig    2020-09-24 15:21:18.403193900 +0900
+++ _config_personal.py 2020-09-24 15:21:51.567736700 +0900
@@ -158,7 +158,7 @@ if 0:
 #---------------------------------------------------------------------------------------------------
 # Everything プログラムを起動するキーを指定する

-if 0
+if 0:
     # Everything を起動するキーを指定する
     everything_key = "C-A-e"

**Comment by smzht** [comment]
報告ありがとうございます。以下で対応しました。よろしくお願いします。

https://github.com/smzht/fakeymacs/commit/a7c11840ee2f532c73baf4e59ce605084042c0e9

**Comment by camelken** [comment]
ありがとうございます。
確認いたしました。
